name: trestus
version: 1.0.1
summary: Static status page generator that uses a Trello board as a data source
description: Trestus is a static page generator that generates a web service status page from a Trello board displaying outage information for customers to follow along when there are issues.
confinement: strict

apps:
  trestus:
    command: usr/bin/trestus
    plugs:
      - home
      - network
      - network-bind

parts:
  python:
    plugin: python3
    source: .
    filesets:
      pylibs:
        - usr/bin/python3
        - usr/bin/python3.5
        - usr/bin/trestus
        - usr/lib/python3/
        - usr/lib/python3.5/
    snap:
      - $pylibs
